name: movie_browser
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  get_it: ^9.2.0
  dio: ^5.9.1
  hive: ^2.2.3
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  flutter_bloc: ^9.1.1
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  freezed: ^3.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
